version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gonzalesRoot
      MYSQL_DATABASE: db_usuarios
      MYSQL_USER: gonzales
      MYSQL_PASSWORD: gonzales123
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: gonzales
      DATABASE_PASSWORD: gonzales123
      DATABASE_NAME: db_usuarios
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    # command: npm start
    command: sh -c "npx wait-port db:3306 && npm start"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge